name: "Frontend: Build and Push Docker Image to GHCR"
on:
  push:
    branches: [main]
    paths:
      - frontend/**
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image name
        id: image
        run: echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/quiz-frontend:latest" >> $GITHUB_ENV
      - name: Build and push for arm64
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          platforms: linux/arm64
          tags: ${{ env.IMAGE_NAME }}
