name: Build and Push Docker Image to GHCR
on:
  push:
    branches: [main]
    paths:
      - '**/Dockerfile'
      - '.github/workflows/docker-publish.yml'
      - '**/*.ts'
      - '**/*.js'
      - '**/*.json'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image name
        id: image
        run: echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/your-image-name:latest" >> $GITHUB_ENV
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .
      - name: Push Docker image
        run: docker push $IMAGE_NAME
